### ISSUE TITLE
Dual channel image not registered

### ISSUE THREAD

**Issue by JurgenKriel** [ekatrukha/ComDet#2]
Hi there

I'm trying to detect two sets of vesicles in a dual channel image for colocalization, but when running your plugin only one channel is registered. Any suggestions on how to fix this?

**Comment by ekatrukha** [comment]
Hello Jurgen,

Is it a composite two-channel image?
The best way to solve it, I think,
if you'll mail me (katpyxa at gmail.com) your image in question
together with parameters values that you used for detection.

Cheers,
Eugene

**Comment by JurgenKriel** [comment]
Hi, I see now that I had to run 'Make Composite'  even though the original was a dual channel image. The plugin works wonderfully thanks!
