### ISSUE TITLE
Can we select some detection parameters separately for each channel?

### ISSUE THREAD

**Issue by redbybeing** [ekatrukha/ComDet#3]
Hi, 
I use ComDet a lot, and it's a great plugin!
However, I wish there was a modification of this plugin, and I wonder if that is possible.
So when I run ComDet for a two-channel image, I have the options for checking 'Include larger particles?' and 'Segment larger particles (slow)?'.
I hope I can adjust these two options separately for each channel.
Because checking these options for one channel may work well (more precise detection of spots as I want), but not for the other channel.
I look forward to your opinion.
Thank you very much.
Best,
Jiseok

**Comment by ekatrukha** [comment]
Hello Jiseok,

I've added this option in the latest version (0.5.0).

Cheers,
Eugene
