### ISSUE TITLE
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: jaolho/data/lma/implementations/JAMAMatrix

### ISSUE THREAD

**Issue by christofidi** [ekatrukha/ComDet#6]
Good evening,

I am trying to use your code and I got this exception on this function:

public static double estimateSigma(int[] img, ConnCompProperties roi, double[] pos, int width, double initGuess){
        Gauss2D g2d = new Gauss2D();
        double[][] dataXY = getData(img, roi, width);
        double[] theta = getInitParameters(dataXY, pos, initGuess);
        LMA lma = new LMA(g2d, theta, dataXY);
        lma.fit();
        System.out.println("Iteration : " + lma.iterationCount);
        System.out.println("chi2 : " + lma.chi2);
        System.out.println("Theta vector : ["
                + DoubleStr.double2str(lma.parameters[0]) + ", "        /*
                                                                        * The array of fit parameters (a.k.a, the a-vector).
                                                                        */
                + DoubleStr.double2str(lma.parameters[1]) + ", "
                + DoubleStr.double2str(lma.parameters[2]) + ", "
                + DoubleStr.double2str(lma.parameters[3]) + ", "
                + DoubleStr.double2str(lma.parameters[4]) + ", "
                + DoubleStr.double2str(lma.parameters[5]) );

        double sigma = (lma.parameters[3]+lma.parameters[4])/2.0;
        return sigma;
    }

I am thinking there may be any incompatibility in the java version or the jars. I am using java 8.

Thank you very much! Any help will be appreciated

**Comment by ekatrukha** [comment]
Hello @christofidi,

java 8 is not a problem.
I guess you are using it in ImageJ, in this case you are missing one extra jar file (JAMA library).
Here is link [for download](https://math.nist.gov/javanumerics/jama/Jama-1.0.3.jar)
you can download and put it in plugins folder where ComDet jar is.

Let me know if it works,

Cheers,
Eugene

**Comment by christofidi** [comment]
Thank you very much for your timely response! I was missing a jar indeed , I added it and it runs perfectly now.

Have a good day,
Georgia
