### ISSUE TITLE
Python version available?

### ISSUE THREAD

**Issue by ajinkya-kulkarni** [ekatrukha/ComDet#7]
Hello team, thanks for this repo! I was wondering if a python version of this script is available, where I can read in my image and extract bounding boxes or even a labelled image having the detected dots. 
Thanks!

**Comment by ekatrukha** [comment]
Hey, thanks for your kind words.

No, there is no python implementation.
But you can call it from [pyimagej](https://github.com/imagej/pyimagej). 
If you initialize it with [local installation](https://py.imagej.net/en/latest/01-Starting-PyImageJ.html#ways-to-initialize), you can run [IJ plugins from python](https://py.imagej.net/en/latest/07-Running-Macros-Scripts-and-Plugins.html#example-run-a-plugin-ij-py-run-plugin).

From there you can get Results table with boxes and, in principle, labelled image.

Cheers,
Eugene
