### ISSUE TITLE
Prebuild version

### ISSUE THREAD

**Issue by J-Cake** [ekatrukha/ComDet#8]
Hi I'm looking to install ComDet but seem to be struggling to build it myself. Is there a prebuilt image I can download from GitHub? (I see you have an actions workflow, perhaps the final JAR file can be added to the release?)

Cheers

**Comment by ekatrukha** [comment]
Hello @J-Cake,

you are right, it got lost in the recent update.
I've uploaded latest jar file to the releases, see [here](https://github.com/UU-cellbiology/ComDet/releases/tag/0.5.5).

**Comment by J-Cake** [comment]
Thank uuuu
